# NumPy

In [1]:
# https://www.geeksforgeeks.org/introduction-to-numpy/

In [2]:
# importing NumPy
import numpy as np

# Basic Commands using NumPy

- **arr.ndim**: Number of dimensions (axes) of the array `arr`.
- **arr.shape**: Tuple indicating the array's shape, i.e., dimensions along each axis.
- **arr.size**: Total number of elements in the array `arr`.
- **arr.dtype**: Data type of the elements in the array `arr`.
- **id(arr)**: Unique identifier for the array object `arr` in Python's memory.
- **type(arr)**: Type of the array object `arr`, usually `numpy.ndarray`.
- **len(arr)**: Length of the first dimension of the array `arr`.
- **np.array(arr)**: Creates a new NumPy array from the iterable `arr`.
- **np.copy(arr)**: Copies the np.array to a new NumPy array `arr` .

# Array Creation

- **np.zeros**: Create an array filled with `zeros`.
- **np.ones**: Create an array filled with `ones`.
- **np.empty** : Create an `uninitialized` array.
- **np.arange**: Create an array with a `range of values`.
- **np.random.randn**: Create an array of `random natural values`.
- **np.random.randint**: Create an array of `random integers`.
- **np.full**: Create an array filled with a `specified value`.
- **np.eye**: Create a `2D identity matrix`.

# Array Manipulation

- **np.reshape**: `Reshape` an array.
- **np.flatten**: `Flatten` an array into a 1D array.
- **np.transpose**: `Transpose` dimensions of an array.
- **np.concatenate**: `Concatenate` arrays along a specified axis.
- **np.split**: `Split` an array into multiple sub-arrays.
- **np.resize**: `Resize` an array.

# Mathematical Functions

- **np.sum**: `Sum` of array elements.
- **np.mean**: `Mean` of array elements.
- **np.std**: `Standard deviation` of array elements.
- **np.var**: `Variance` of array elements.
- **np.min**: `Minimum` value in an array.
- **np.max**: `Maximum` value in an array.
- **np.argmin**: `Index` of `minimum` value.
- **np.argmax**: `Index` of `maximum` value.
- **np.sqrt**: `Square root` of each element.
- **np.exp**: `Exponential` of each element.
- **np.dot**: `Dot produc`t of two arrays.
- **np.cross**: `Cross product` of two arrays.

# Statistical Operations

- **np.histogram**: Compute `histogram` of an array.
- **np.percentile**: Compute the `nth percentile` of an array.
- **np.corrcoef**: Compute `correlation coefficients`.

# Logical Operations

- **np.logical_and**: Element-wise logical `AND`.
- **np.logical_or**: Element-wise logical `OR`.
- **np.logical_not**: Element-wise logical `NOT`.

# Sorting, Searching and Counting

- **np.sort**: `Sort` elements of an array.
- **np.argsort**: `Indices` that would sort an array.
- **np.searchsorted**: Find indices where elements should be inserted to maintain order.
- **np.unique**: Find `unique` elements in an array.
- **np.bincount**: `Count occurrences` of each value in an array of non-negative integers.

# File Operations

- **np.load**: Load arrays from .npy files.
- **np.save**: Save arrays to .npy files.
- **np.savetxt**: Save arrays to text files.
- **np.loadtxt**: Load data from text files.

# Basic Commands Examples

In [3]:
# Create a NumPy array for demonstration
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
# arr.ndim: Number of dimensions (axes) of the array arr
print("Number of dimensions:", arr.ndim)

Number of dimensions: 2


In [5]:
# arr.shape: Tuple indicating the array's shape
print("Shape of the array:", arr.shape)

Shape of the array: (2, 3)


In [6]:
# arr.size: Total number of elements in the array arr
print("Total number of elements:", arr.size)

Total number of elements: 6


In [7]:
# arr.dtype: Data type of the elements in the array arr
print("Data type of the array elements:", arr.dtype)

Data type of the array elements: int32


In [8]:
# id(arr): Unique identifier for the array object arr in Python's memory
print("Unique identifier of the array object:", id(arr))

Unique identifier of the array object: 3170090518736


In [10]:
# type(arr): Type of the array object arr
print("Type of the array object:", type(arr))

Type of the array object: <class 'numpy.ndarray'>


In [11]:
# len(arr): Length of the first dimension of the array arr
print("Length of the first dimension:", len(arr))

Length of the first dimension: 2


# Array Creation Examples

In [12]:
# np.array(arr): Creates a new NumPy array from the iterable arr
new_arr = np.array(arr)
print("New NumPy array from arr:\n", new_arr)

New NumPy array from arr:
 [[1 2 3]
 [4 5 6]]


In [13]:
# np.copy(arr): Copies the NumPy array arr to a new array
arr_copy = np.copy(arr)
print("Copied NumPy array:\n", arr_copy)

Copied NumPy array:
 [[1 2 3]
 [4 5 6]]


In [14]:
# np.zeros: Create an array filled with zeros
zeros_arr = np.zeros((2, 3))  # Creates a 2x3 array filled with zeros
print("Array filled with zeros:\n", zeros_arr)

Array filled with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# np.ones: Create an array filled with ones
ones_arr = np.ones((3, 2))  # Creates a 3x2 array filled with ones
print("Array filled with ones:\n", ones_arr)

Array filled with ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
# np.empty: Create an uninitialized array
empty_arr = np.empty((2, 2))  # Creates a 2x2 uninitialized array (values can be garbage)
print("Uninitialized array:\n", empty_arr)

Uninitialized array:
 [[2.12199579e-314 6.01334412e-154]
 [5.98807563e-321 3.79442416e-321]]


In [17]:
# np.arange: Create an array with a range of values
range_arr = np.arange(1, 10, 2)  # Creates an array from 1 to 9 (exclusive) with step 2
print("Array with range of values:", range_arr)

Array with range of values: [1 3 5 7 9]


In [18]:
# np.random.randn: Create an array of random values from a normal distribution
randn_arr = np.random.randn(3, 3)  # Creates a 3x3 array of random values from a standard normal distribution
print("Array of random values (standard normal distribution):\n", randn_arr)

Array of random values (standard normal distribution):
 [[-0.9182247   0.75203783 -0.49045956]
 [ 1.03717228  1.77593421 -1.35457954]
 [ 2.47255838  0.35393412 -0.06488311]]


In [19]:
# np.random.randint: Create an array of random integers
randint_arr = np.random.randint(1, 10, size=(2, 3))  # Creates a 2x3 array with random integers from 1 to 9
print("Array of random integers:\n", randint_arr)

Array of random integers:
 [[8 6 5]
 [1 1 3]]


In [20]:
# np.full: Create an array filled with a specified value
full_arr = np.full((2, 4), 5)  # Creates a 2x4 array filled with the value 5
print("Array filled with specified value:\n", full_arr)

Array filled with specified value:
 [[5 5 5 5]
 [5 5 5 5]]


In [21]:
# np.eye: Create a 2D identity matrix
identity_matrix = np.eye(3)  # Creates a 3x3 identity matrix
print("2D Identity matrix:\n", identity_matrix)

2D Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array Manipulation Examples

In [22]:
# Create NumPy arrays for demonstration
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

In [23]:
# np.reshape: Reshape an array
reshaped_arr = np.reshape(arr1, (3, 2))  # Reshape arr1 to a 3x2 array
print("Reshaped array:\n", reshaped_arr)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


In [24]:
# np.flatten: Flatten an array into a 1D array
flattened_arr = arr1.flatten()  # Flatten arr1 into a 1D array
print("Flattened array:", flattened_arr)

Flattened array: [1 2 3 4 5 6]


In [25]:
# np.transpose: Transpose dimensions of an array
transposed_arr1 = np.transpose(arr1)  # Transpose arr1 (2x3 -> 3x2)
print("Transposed array (arr1):\n", transposed_arr1)
transposed_arr2 = arr2.T  # Shorthand for transpose
print("Transposed array (arr2):\n", transposed_arr2)

Transposed array (arr1):
 [[1 4]
 [2 5]
 [3 6]]
Transposed array (arr2):
 [[ 7  9]
 [ 8 10]]


In [26]:
# np.concatenate: Concatenate arrays along a specified axis
concatenated_arr = np.concatenate((arr1, arr2), axis=1)  # Concatenate along columns (axis=1)
print("Concatenated array along axis 1:\n", concatenated_arr)

Concatenated array along axis 1:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [29]:
# np.split: Split an array into multiple sub-arrays
split_arr = np.split(arr1, 3, axis=1)  # Split arr1 into 2 sub-arrays along columns
print("Split array along axis 1:\n", split_arr)

Split array along axis 1:
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [28]:
# np.resize: Resize an array
resized_arr = np.resize(arr1, (3, 3))  # Resize arr1 to a 3x3 array
print("Resized array:\n", resized_arr)

Resized array:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


# Mathematical Functions Examples

In [30]:
# Create a NumPy array for demonstration
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [31]:
# np.sum: Sum of array elements
sum_arr = np.sum(arr)  # Sum of all elements in arr
print("Sum of array elements:", sum_arr)

Sum of array elements: 21


In [32]:
# np.mean: Mean of array elements
mean_arr = np.mean(arr)  # Mean of all elements in arr
print("Mean of array elements:", mean_arr)

Mean of array elements: 3.5


In [33]:
# np.std: Standard deviation of array elements
std_arr = np.std(arr)  # Standard deviation of all elements in arr
print("Standard deviation of array elements:", std_arr)

Standard deviation of array elements: 1.707825127659933


In [34]:
# np.var: Variance of array elements
var_arr = np.var(arr)  # Variance of all elements in arr
print("Variance of array elements:", var_arr)

Variance of array elements: 2.9166666666666665


In [35]:
# np.min: Minimum value in an array
min_arr = np.min(arr)  # Minimum value in arr
print("Minimum value in array:", min_arr)

Minimum value in array: 1


In [36]:
# np.max: Maximum value in an array
max_arr = np.max(arr)  # Maximum value in arr
print("Maximum value in array:", max_arr)

Maximum value in array: 6


In [37]:
# np.argmin: Index of minimum value
argmin_arr = np.argmin(arr)  # Index of the minimum value in arr (flattened)
print("Index of minimum value in array:", argmin_arr)

Index of minimum value in array: 0


In [38]:
# np.argmax: Index of maximum value
argmax_arr = np.argmax(arr)  # Index of the maximum value in arr (flattened)
print("Index of maximum value in array:", argmax_arr)

Index of maximum value in array: 5


In [39]:
# np.sqrt: Square root of each element
sqrt_arr = np.sqrt(arr)  # Element-wise square root of arr
print("Square root of array elements:\n", sqrt_arr)

Square root of array elements:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [40]:
# np.exp: Exponential of each element
exp_arr = np.exp(arr)  # Element-wise exponential of arr
print("Exponential of array elements:\n", exp_arr)

Exponential of array elements:
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [41]:
# np.dot: Dot product of two arrays
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
dot_product = np.dot(arr1, arr2)  # Dot product of arr1 and arr2
print("Dot product of two arrays:", dot_product)

Dot product of two arrays: 11


In [42]:
# np.cross: Cross product of two arrays
cross_product = np.cross(arr1, arr2)  # Cross product of arr1 and arr2
print("Cross product of two arrays:", cross_product)

Cross product of two arrays: -2


# Statistical Operations Examples

In [43]:
# Create a NumPy array for demonstration
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [44]:
# np.histogram: Compute histogram of an array
hist, bins = np.histogram(arr, bins=5)  # Compute histogram with 5 bins
print("Histogram values:", hist)
print("Histogram bins:", bins)

Histogram values: [2 2 2 2 2]
Histogram bins: [ 1.   2.8  4.6  6.4  8.2 10. ]


In [45]:
# np.percentile: Compute the nth percentile of an array
percentile_50 = np.percentile(arr, 50)  # 50th percentile (median)
percentile_90 = np.percentile(arr, 90)  # 90th percentile
print("50th percentile (median):", percentile_50)
print("90th percentile:", percentile_90)

50th percentile (median): 5.5
90th percentile: 9.1


In [48]:
# Generate a 2D array for np.corrcoef demonstration
arr2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print("2 Dimension Array:", arr2d)

2 Dimension Array: [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [47]:
# np.corrcoef: Compute correlation coefficients
corrcoef = np.corrcoef(arr2d)  # Compute correlation matrix for rows of arr2d
print("Correlation coefficients:\n", corrcoef)

Correlation coefficients:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Logical Operations Examples

In [49]:
# Create NumPy arrays for demonstration
arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

In [50]:
# np.logical_and: Element-wise logical AND
logical_and_arr = np.logical_and(arr1, arr2)
print("Element-wise logical AND:\n", logical_and_arr)

Element-wise logical AND:
 [ True False False False]


In [51]:
# np.logical_or: Element-wise logical OR
logical_or_arr = np.logical_or(arr1, arr2)
print("Element-wise logical OR:\n", logical_or_arr)

Element-wise logical OR:
 [ True  True  True False]


In [52]:
# np.logical_not: Element-wise logical NOT
logical_not_arr1 = np.logical_not(arr1)
logical_not_arr2 = np.logical_not(arr2)
print("Element-wise logical NOT (arr1):\n", logical_not_arr1)
print("Element-wise logical NOT (arr2):\n", logical_not_arr2)

Element-wise logical NOT (arr1):
 [False False  True  True]
Element-wise logical NOT (arr2):
 [False  True False  True]


# Sorting, Searching and Counting Examples

In [53]:
# Create a NumPy array for demonstration
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

In [54]:
# np.sort: Sort elements of an array
sorted_arr = np.sort(arr)  # Sort arr in ascending order
print("Sorted array:", sorted_arr)

Sorted array: [1 1 2 3 4 5 5 6 9]


In [55]:
# np.argsort: Indices that would sort an array
indices_sorted = np.argsort(arr)  # Indices that would sort arr
print("Indices that would sort the array:", indices_sorted)

Indices that would sort the array: [1 3 6 0 2 4 8 7 5]


In [56]:
# np.searchsorted: Find indices where elements should be inserted to maintain order
search_indices = np.searchsorted(sorted_arr, [0, 3, 8])  # Find insertion points for 0, 3, and 8
print("Indices to maintain order:", search_indices)

Indices to maintain order: [0 3 8]


In [57]:
# np.unique: Find unique elements in an array
unique_elements = np.unique(arr)  # Find unique elements in arr
print("Unique elements in array:", unique_elements)

Unique elements in array: [1 2 3 4 5 6 9]


In [58]:
# np.bincount: Count occurrences of each value in an array of non-negative integers
bincount_arr = np.bincount(arr)  # Count occurrences of each value in arr
print("Bincount of array elements:", bincount_arr)

Bincount of array elements: [0 2 1 1 1 2 1 0 0 1]


# File Operations Examples

In [59]:
# Create a NumPy array for demonstration
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [60]:
# Save array to .npy file
# np.save('my_array.npy', arr)

In [61]:
# Load array from .npy file
# loaded_arr = np.load('my_array.npy')

In [62]:
# print("Loaded array from .npy file:")
# print(loaded_arr)

# END